# Generated by Django 4.2.13 on 2024-06-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='isWin',
            field=models.CharField(default='未知', max_length=1024),
        ),
        migrations.AddField(
            model_name='history',
            name='matchTime',
            field=models.CharField(default='2024.6.1', max_length=1024),
        ),
        migrations.AddField(
            model_name='history',
            name='matchType',
            field=models.CharField(default='人机对战', max_length=1024),
        ),
    ]
