# Generated by Django 4.2.13 on 2024-05-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
