# Generated by Django 4.2.13 on 2024-06-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.CharField(default='empty', max_length=1024),
        ),
    ]
